### ISSUE TITLE
Link https://github.com/emailjs/emailjs-mime-codec/blob/master/src/mimecodec.js for "mimecodec.js" script is broken.

### ISSUE THREAD

**Issue by vvelizariy** [emailjs/emailjs-mime-codec#17]
Link https://github.com/emailjs/emailjs-mime-codec/blob/master/src/mimecodec.js on main page for "mimecodec.js" script is broken.
As temporary solution uploaded here substitution "https://gist.github.com/vvelizariy/9c8c1c59afc03d23f433a23de2631a99". Wasted a lot of time searching for existing one with no luck, so maybe someone will need it too.

**Comment by felixhammerl** [comment]
I don't quite understand why a broken link is an issue here. Please use the npm package.
